services:
  db:
    ports:
      - 3306:3306
    volumes:
      - /srv/db/wikiapiary/mysql:/var/lib/mysql
  web:
    image: canasta-w8y:1.0
  caddy:
    image: alpine:latest
    restart: "no" 
    entrypoint: ["echo", "Caddy is disabled"]
  varnish:
    ports:
      - 80:80
