services:
  web:
    image: canasta:latest
    volumes:
      - ${BUILD_DIR}/resources/WikiApiary_Bee.png:/var/www/mediawiki/w/resources/assets/WikiApiary_Bee.png
      - ${BUILD_DIR}/resources/favicon.ico:/var/www/mediawiki/w/resources/assets/favicon.ico
      - ${BUILD_DIR}/resources/Monitored_by_WikiApiary.png:/var/www/mediawiki/w/resources/assets/Monitored_by_WikiApiary.png
      - ${BUILD_DIR}/resources/wmf-cloud.png:/var/www/mediawiki/w/resources/assets/wmf-cloud.png
  scripts:
    image: scripts:latest
    build:
      context: ${BUILD_DIR}/scripts_image
    restart: unless-stopped
    environment:
      - WIKIAPIARY_DB_USERNAME=${WIKIAPIARY_DB_USERNAME}
      - WIKIAPIARY_DB_PASSWORD=${WIKIAPIARY_DB_PASSWORD}
      - WIKIAPIARY_DB_HOST=${WIKIAPIARY_DB_HOST}
      - WIKIAPIARY_DB_PORT=${WIKIAPIARY_DB_PORT}
      - WIKIAPIARY_DB_SCHEMA=${WIKIAPIARY_DB_SCHEMA}
      - WIKIAPIARY_USERNAME=${WIKIAPIARY_USERNAME}
      - WIKIAPIARY_URL=${WIKIAPIARY_URL}
    volumes:
      - ./extensions:/root/extensions
  caddy:
    image: alpine:latest
    restart: "no" 
    entrypoint: ["echo", "Caddy is disabled"]
  varnish:
    ports:
      - 80:80
