FROM canasta:dev
COPY WikiApiary_Bee.png /var/www/mediawiki/w/resources/assets/WikiApiary_Bee.png
COPY favicon.ico /var/www/mediawiki/w/resources/assets/favicon.ico
COPY Monitored_by_WikiApiary.png /var/www/mediawiki/w/resources/assets/Monitored_by_WikiApiary.png
COPY wmf-cloud.png /var/www/mediawiki/w/resources/assets/wmf-cloud.png
